sudo: required
services: 
  - docker

before_install:
  - docker build -t sanveersingh/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true sanveersingh/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-263354746789"
  bucket_path: "frontend"
  on: 
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"

